version: "3"
services:
  ms-user-repo-docker:
    image: ms-user-repo-docker
    ports:
      - "9000:9191"
    depends_on:
      - db
  ms-file-mgmt-docker:
    image: ms-file-mgmt-docker
    ports:
      - "8000:8181"
    depends_on:
      - db
  db:
    image: postgres:9.3.6
    #volumes: 
    #  - D:/_ms/storage-poc-docker-compose/storage-poc-docker-compose/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: asecurepassword
    ports:
      - "5435:5432"

