eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty:  0
  instance:
    preferIpAddress: true
---
spring:
  profiles: server1
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
---
spring:
  profiles: server2
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    
    
#-Deureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
    